# Generated by Django 4.2.8 on 2024-03-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectedPlayer',
        ),
    ]
