# Generated by Django 4.2.8 on 2024-02-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_avatar_alter_user_custom_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_field',
            field=models.CharField(max_length=255),
        ),
    ]
