# Generated by Django 4.2.8 on 2024-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
