# Generated by Django 4.2.8 on 2024-04-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_user_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
