# Generated by Django 4.2.8 on 2024-04-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_user_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profil_pic'),
        ),
    ]
