# Generated by Django 4.2.8 on 2024-04-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_match'),
        ('registration', '0011_user_profil_pic'),
    ]

    operations = [
    ]
