# Generated by Django 4.2.8 on 2024-04-11 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_merge_0011_match_0011_user_profil_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status', models.CharField(max_length=10)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tic_opponent', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tic_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
