# Generated by Django 4.2.8 on 2024-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_ticmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
